CL\Slack\Model\SimpleMessage:
    properties:
        ts:
            type: string
        type:
            type: string
        subtype:
            type: string
        channel:
            type: string
        user:
            type: string
        username:
            type: string
        text:
            type: string
        attachments:
            type: array<CL\Slack\Model\Attachment>
