CL\Slack\Payload\AbstractPayloadResponse:
    properties:
        ok:
            type: boolean
        error:
            type: string
        needed:
            type: string
        provided:
            type: string
